### ISSUE TITLE
Question / feature-request: delay the linting (of, only, codespell)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kaste/SublimeLinter-contrib-codespell#2]
I am aware that SublimeLinter itself has a configurable delay (before it acts). However - perhaps given the slapdash way that, initially, I type comments - it would be good were the codespell linting to have its own configurable delay. Or so it seems to me. Is there currently an option for that? I tried:

```
// SublimeLinter Settings - User
{
  [. . . .]
        "codespell": {
            "delay": 20,
            "selector": "-text.plain",
            "styles": [
                {
                    "scope": "region.redish",
                    "annotation": "{msg}",
                    "phantom": ""
                }
            ]
        },
    },
}
```

But seemingly to no avail.

An alternative with which I would be happy would be for codespell to lint only upon file saving.

**Comment by kaste** [comment]
`lint_mode` is available here (https://www.sublimelinter.com/en/latest/linter_settings.html#lint-mode) but *delay* is not.  This would probably need an implementation in SublimeLinter core.  I might remember this wrong but I think these linter settings are currently not available in the early phase where the "delay" is currently read.  IIRC we read the delay *before* we elect and assign linters to the view because that is costly in itself.

**Comment by LinuxOnTheDesktop** [comment]
`lint_mode` - set to `load_save` - will do for me and, I suspect, others. Thanks.
