### ISSUE TITLE
Cannot ignore valid keywords

### ISSUE THREAD

**Issue by FichteFoll** [kaste/SublimeLinter-contrib-codespell#3]
Rust uses a keyword named `crate` to refer to its bundles. Codespell likes to correct this to `create`, so I figured I would tell SL to not run the linter for valid keywords. However, that turns out to not work as expected because the addition of `- keyword` to the codespell selector does not appear to have an effect.

My config is basically the one mentioned in the README plus the extra difference selector and I can confirm the styles and `- text` selector to be working.

```
        "codespell": {
            "selector": "source - text - keyword",
            "styles": [
                {
                    "scope": "region.yellowish",
                    "annotation": "{msg}",
                    "phantom": ""
                }
            ]
        },
```

Is the selector only executed against the first character of a view?

Example Rust code:
```rs
#[cfg(test)]
mod tests {
    extern crate test;
    #[test]
    fn simple_test() {
        assert_eq!(1 + 1, 2);
    }
}
```

**Comment by kaste** [comment]
Hi 👋!  Clever idea to use selector for something like that, but you're right

> Is the selector only executed against the first character of a view?

That's correct.  By default and since 4.26.0 https://github.com/SublimeLinter/SublimeLinter/releases/tag/4.26.0, only the first char counts.  You can set `enable_cells` to switch to the old behavior.  The old behavior always had the risk of splitting a view into too many parts.  Remember, every part needs to be handled separately, for each one we need a process.  

But you can just tell codespell to ignore "crate".  `-L crate` on the command line.  Also possible in a config file. A `pyproject.toml` file looks weird in a rust project, `.codespellrc` is also a valid config filename.

**Comment by FichteFoll** [comment]
Thanks for the hint. I'll go with adjusting `args`, then.
